services:
  api:
    container_name: api
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./server/.env
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:alpine
    restart: unless-stopped
    env_file:
      - ./server/.env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
